// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication6.Models;

public partial class Dcode
{
    public string DcodeId { get; set; }

    public string DcodeName { get; set; }

    public virtual ICollection<Downtimes> Downtimes { get; set; } = new List<Downtimes>();
}