// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication6.Models;

public partial class Downtimes
{
    public int DowntimeId { get; set; }

    public TimeSpan? DowntimeStart { get; set; }

    public TimeSpan? DowntimeEnd { get; set; }

    public TimeSpan? DowntimeHour { get; set; }

    public int OutputId { get; set; }

    public string DcodeId { get; set; }

    public virtual Dcode Dcode { get; set; }

    public virtual Outputs Output { get; set; }
}