// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using WebApplication6.Models;

namespace WebApplication6.Models
{
    public partial interface IDBOEEContextProcedures
    {
        Task<int> GenerateOutput2Async(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
