// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebApplication6.Models;

public partial class Outputs
{
    public int OutputId { get; set; }

    [DataType(DataType.Date)]
    public DateTime OutputDate { get; set; }
    public int? MachineId { get; set; }

    public int? TimeId { get; set; }

    public int? ToyId { get; set; }

    public int? OutputQTY { get; set; }

    public int? Crate { get; set; }

    public int? DefectId { get; set; }

    public int? DefectQty { get; set; }

    public virtual Defects Defect { get; set; }

    public virtual ICollection<Downtimes> Downtimes { get; set; } = new List<Downtimes>();

    public virtual Machines Machine { get; set; }

    public virtual Times Time { get; set; }

    public virtual Toys Toy { get; set; }
}