// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication6.Models;

public partial class Shifts
{
    public int ShiftId { get; set; }

    public string ShiftName { get; set; }
}