// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication6.Models;

public partial class Times
{
    public int TimeId { get; set; }

    public string Tstart { get; set; }

    public string Tend { get; set; }

    public string Shift { get; set; }

    public virtual ICollection<Outputs> Outputs { get; set; } = new List<Outputs>();
}