// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication6.Models;

public partial class Toys
{
    public int ToyId { get; set; }

    public string ToyName { get; set; }

    public decimal? ToyPlan { get; set; }

    public int? CategoryId { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<Outputs> Outputs { get; set; } = new List<Outputs>();
}